### ISSUE TITLE
Selenium-server-standalone version selection

### ISSUE THREAD

**Issue by thomasKuilman** [ropensci/RSelenium#65] opened 2016-01-01 22:28 UTC
Hi,

While browsing the RSelenium code I realised that the code to select the most recent version of the Selenium standalone server is incorrect. Please refer to the sample below, where selenium-server-standalone-2.48.0.jar (and not the newer selenium-server-standalone-2.48.2.jar) would be selected for downloading.

Replacing the following line

selJAR <- selJAR[order(as.numeric(gsub("(.*)/.*", "\\1", selJAR)), decreasing = TRUE)][1]

for

selJAR <- selJAR[order(gsub(".*-(.*).jar$", "\\1", selJAR), decreasing = TRUE)][1]

would fix things.

Thanks,

Thomas

> selJAR[order(as.numeric(gsub("(.*)/.*", "\\1", selJAR)), decreasing = TRUE)]
 [1] "2.48/selenium-server-standalone-2.48.0.jar" "2.48/selenium-server-standalone-2.48.1.jar" "2.48/selenium-server-standalone-2.48.2.jar" "2.47/selenium-server-standalone-2.47.0.jar" "2.47/selenium-server-standalone-2.47.1.jar"
 [6] "2.46/selenium-server-standalone-2.46.0.jar" "2.45/selenium-server-standalone-2.45.0.jar" "2.44/selenium-server-standalone-2.44.0.jar" "2.43/selenium-server-standalone-2.43.0.jar" "2.43/selenium-server-standalone-2.43.1.jar"
[11] "2.42/selenium-server-standalone-2.42.0.jar" "2.42/selenium-server-standalone-2.42.1.jar" "2.42/selenium-server-standalone-2.42.2.jar" "2.41/selenium-server-standalone-2.41.0.jar" "2.40/selenium-server-standalone-2.40.0.jar"
[16] "2.39/selenium-server-standalone-2.39.0.jar"

**Comment by daattali** [comment] 2016-07-29 08:58
I just noticed this as well and it was the cause of a 3-hour bug for me. Manually downloading the correct version fixed RSelenium for me.  This should be fixed :)

**Comment by daattali** [comment] 2016-07-29 09:11
@thomasKuilman I think the correct behaviour would be to take the most recent version that is not a beta version. So I modified your solution so that beta versions are excluded, and made a PR

**Comment by johndharrison** [comment] 2016-07-29 13:12
Thank you @thomasKuilman and @daattali a fix has been committed thanks to code from @daattali.

**Closed by johndharrison** 2016-07-29 13:12 UTC
