### ISSUE TITLE
startserver() issue 

### ISSUE THREAD

**Issue by edritf** [ropensci/RSelenium#94] opened 2016-10-06 09:39 UTC
Hi, when I run the startServer() command I get the following warning. Afterwards, the Open() funtion does not work either. I think It is a problem with the Server location, but I am not sure. Do you have an idea? thanks! 

Warning messages:
1: startServer is deprecated.
Users in future can find the function in file.path(find.package("RSelenium"), "example/serverUtils").
The sourcing/starting of a Selenium Server is a users responsiblity. 
Options include manually starting a server see vignette("RSelenium-basics", package = "RSelenium")
and running a docker container see  vignette("RSelenium-docker", package = "RSelenium") 
2: running command '"wmic" path win32_process get Caption,Processid,Commandline /format:htable' had status 44210 
Error in readHTMLTable(htmlParse(wmicOut), header = TRUE, stringsAsFactors = FALSE) : 
  error in evaluating the argument 'doc' in selecting a method for function 'readHTMLTable': Error in if (file.exists(file) == FALSE) if (!missing(asText) && asText ==  : 
  argument is of length zero

**Comment by johndharrison** [comment] 2016-10-06 10:04
HI @edritf 

1. The startServer and checkServer functions have been marked for deprecation. 

2. Your issue is most likely a duplicate of https://github.com/ropensci/RSelenium/issues/82 .

**Comment by edritf** [comment] 2016-10-06 17:09
Hi, thanks for the answer. I got the Docker container, but I am not able to get the port.

 I even run the command to get the port (docker port <container-name|container-id> 4444) and it says that it can´t find the container name or id... 

In theory I pull the Selenium chrome image correctly, but I can´t continue from there. Thanks for the help

**Closed** 2017-01-25 00:24 UTC
Labels: Deprecated functions
